### ISSUE TITLE
Where are the files : get_mae.py and truth.txt?

### ISSUE THREAD

**Issue by WAYSC** [byungdoh/cmcl21_shared_task#1]
I have already trained your model and yield my_predictions.txt, however, i can't process the last step--"python get_mae.py my_predictions.txt truth.txt" for the lack of get_mae.py and truth.txt.

**Comment by byungdoh** [comment]
Hi Elly,

Sorry about the oversight; I've just added get_mae.py to the repository, and "truth.txt" corresponds to the gold test data available under "Participate > Files > #4 PostEval" on the Shared Task CodaLab page.
